- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/egpu.yml
    - include: tasks/signal.yml
    - include: tasks/bitwarden.yml
